### PR TITLE
develop

### PR DESCRIPTION
**Pull request by nragon**
#72

### CODE REVIEW

**Comment by cedricve** [comment]
nice, can you replace the python part with plain c++? We ship to many different environments, so it would be best to have no dependencies.

**Comment by nragon** [comment]
Hi,
Since dropbox has no official cpp api I thought it would be nice to integrate this with python api since python is also xplatform.
I'm having some issues building the project due to env complications (windows), that's why I've not tested this, but I will try asap.

**Comment by nragon** [comment]
Also, python api for dropbox is official.

**Comment by cedricve** [comment]
@nragon I see, but mixing the project with other dependencies/programming languages is not a best practice. I believe you can simulate the same behaviour with a C++ curl requests.  Also using find_package can cause issues. Our goal is to have a static binary without to much dynamic libraries, so our debian users (Raspbian, Armbian) and avoid dynamic libraries.

If you want to use external projects, we recommend to use Cmake's External_Project feature. https://github.com/kerberos-io/machinery/tree/master/cmake

**Pull request closed without merging**
